version: '3'
services:
  web:
    # Replace username/repo:tag with your name and image details.
    image: '1010124/test-py:release-0.0.12'
    networks:
      - 'webnet'
  redis:
    image: redis
    networks:
      - 'webnet'
    volumes:
      - "/home/docker/data:/data"
    command: redis-server --appendonly yes
  nginx:
        build: nginx
        container_name: elportal-nginx
        working_dir: /app
        ports:
            - 80:80
        links:
            - app
        networks:
            - 'webnet'
networks:
  webnet:
